apiVersion: apps/v1
kind: Deployment
metadata:
  name: guestbook-ui
  annotations:
    app.komodor.com/app: https://github.com/iainfinlayson/argocd-example-apps
    app.komodor.com/app.ref: 2c718d21e137ff7f8a56535ac1275c14bc539d9e
spec:
  replicas: 2
  revisionHistoryLimit: 3
  progressDeadlineSeconds: 15
  selector:
    matchLabels:
      app: guestbook-ui
  template:
    metadata:
      labels:
        app: guestbook-ui
    spec:
      nodeSelector:
        kubernetes.io/hostname: ip-172-31-5-163  # match tainted node
      containers:
      - name: guestbook-ui
        image: gcr.io/heptio-images/ks-guestbook-demo:0.2
        ports:
        - containerPort: 80

