apiVersion: apps/v1
kind: Deployment
metadata:
  name: guestbook-ui
  annotations:
    app.komodor.com/app: https://github.com/iainfinlayson/argocd-example-apps
    app.komodor.com/app.ref: e7c3e70a64e8ab0ef0ce9d5334ebd2916d27d9bc
spec:
  replicas: 2
  revisionHistoryLimit: 3
  progressDeadlineSeconds: 15
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 2
  selector:
    matchLabels:
      app: guestbook-ui
  template:
    metadata:
      labels:
        app: guestbook-ui
    spec:
      containers:
      - image: gcr.io/heptio-images/ks-guestbook-demo:does-not-exist
        name: guestbook-ui
        ports:
        - containerPort: 80

