apiVersion: apps/v1
kind: Deployment
metadata:
  name: guestbook-ui
  annotations:
    app.komodor.com/app: https://github.com/iainfinlayson/argocd-example-apps
    app.komodor.com/app.ref: 2c8d082305f33993a5db3f51506d6cb8687d0142
spec:
  replicas: 2
  revisionHistoryLimit: 3
  progressDeadlineSeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 2
  selector:
    matchLabels:
      app: guestbook-ui
  template:
    metadata:
      labels:
        app: guestbook-ui
    spec:
      containers:
      - name: guestbook-ui
        image: gcr.io/heptio-images/ks-guestbook-demo:0.2
        ports:
        - containerPort: 80
        readinessProbe:
          httpGet:
            path: /nope
            port: 80
          initialDelaySeconds: 1
          periodSeconds: 3
          failureThreshold: 1

