apiVersion: apps/v1
kind: Deployment
metadata:
  name: guestbook-ui
  annotations:
    app.komodor.com/app: https://github.com/iainfinlayson/argocd-example-apps
    app.komodor.com/app.ref: 9fec648797878d5f3f393ce504ecbf71558ef4c9
spec:
  replicas: 2
  revisionHistoryLimit: 3
  progressDeadlineSeconds: 60
  selector:
    matchLabels:
      app: guestbook-ui
  template:
    metadata:
      labels:
        app: guestbook-ui
    spec:
      containers:
      - name: guestbook-ui
        image: gcr.io/heptio-images/ks-guestbook-demo:0.2
        ports:
        - containerPort: 80
        volumeMounts:
        - name: broken-volume
          mountPath: /mnt/broken
      volumes:
      - name: broken-volume
        persistentVolumeClaim:
          claimName: broken-pvc

