apiVersion: apps/v1
kind: Deployment
metadata:
  name: guestbook-ui
  annotations:
    app.komodor.com/app: https://github.com/iainfinlayson/argocd-example-apps
    app.komodor.com/app.ref: 68ff0409bea16957bc9e4303c551b40d51dc9c6e
spec:
  replicas: 2
  revisionHistoryLimit: 3
  progressDeadlineSeconds: 15
  selector:
    matchLabels:
      app: guestbook-ui
  template:
    metadata:
      labels:
        app: guestbook-ui
    spec:
      containers:
      - name: guestbook-ui
        image: busybox
        command: ["sh", "-c", "exit 1"]
        ports:
        - containerPort: 80

