apiVersion: apps/v1
kind: Deployment
metadata:
  name: guestbook-ui
  annotations:
    app.komodor.com/app: https://github.com/iainfinlayson/argocd-example-apps
    app.komodor.com/app.ref: 8fc29e8234acd9d5895203f17a08ee116f3fb452
spec:
  replicas: 2
  revisionHistoryLimit: 3
  progressDeadlineSeconds: 60
  selector:
    matchLabels:
      app: guestbook-ui
  template:
    metadata:
      labels:
        app: guestbook-ui
    spec:
      nodeSelector:
        kubernetes.io/hostname: ip-172-31-5-163  # match tainted node
      tolerations:
      - key: "demo"
        operator: "Equal"
        value: "chaos"
        effect: "NoSchedule"
      containers:
      - name: guestbook-ui
        image: gcr.io/heptio-images/ks-guestbook-demo:0.2
        ports:
        - containerPort: 80

