apiVersion: apps/v1
kind: Deployment
metadata:
  name: guestbook-ui
  annotations:
    app.komodor.com/app: https://github.com/iainfinlayson/argocd-example-apps
    app.komodor.com/app.ref: cd962e4e9403b98ef8fdaa1c673883ee5766199b
spec:
  replicas: 2
  revisionHistoryLimit: 3
  progressDeadlineSeconds: 15
  selector:
    matchLabels:
      app: guestbook-ui
  template:
    metadata:
      labels:
        app: guestbook-ui
    spec:
      containers:
      - name: guestbook-ui
        image: gcr.io/heptio-images/ks-guestbook-demo:0.2
        ports:
        - containerPort: 80
        readinessProbe:
          httpGet:
            path: /this-does-not-exist
            port: 80
          initialDelaySeconds: 2
          periodSeconds: 5

