apiVersion: apps/v1
kind: Deployment
metadata:
  name: guestbook-ui
  annotations:
    app.komodor.com/app: https://github.com/iainfinlayson/argocd-example-apps
    app.komodor.com/app.ref: bbb8d6b80c77c9bc19902475b3e409297f7adc90
spec:
  replicas: 2
  revisionHistoryLimit: 3
  progressDeadlineSeconds: 15
  selector:
    matchLabels:
      app: guestbook-ui
  template:
    metadata:
      labels:
        app: guestbook-ui
    spec:
      containers:
      - image: gcr.io/heptio-images/ks-guestbook-demo:0.2
        name: guestbook-ui
        ports:
        - containerPort: 80
      - name: too-greedy
        image: busybox
        command: ["sleep", "3600"]
        resources:
          requests:
            memory: "8Gi"
            cpu: "4000m"
      - name: memory-hog
        image: polinux/stress
        args: ["--vm", "2", "--vm-bytes", "2G", "--timeout", "90s"]
        resources:
          limits:
            memory: "5Gi"
